class La:
    LAM_CONNECTED_FROM_LEFT = 0  # لـ
    LAM_CONNECTED_FROM_BOTH_SIDES = 1  # ـلـ
    LAM_CONNECTED_FROM_BOTH_RIGHT = 2  # ـل
    ISOLATED_LA = 3  # لا
    LA_CONNECTED_FROM_RIGHT = 4  # ـلا
    ISOLATED_LA_WITH_ALIF_WITH_HAMZA_ABOVE = 5  # لأ
    ISOLATED_LA_WITH_ALIF_WITH_HAMZA_BELOW = 6  # لإ
    LA_WITH_ALIF_WITH_HAMZA_ABOVE_CONNECTED_FROM_LEFT = 7  # ـلأ
    LA_WITH_ALIF_WITH_HAMZA_BELOW_CONNECTED_FROM_LEFT = 8  # ـلإ
